### ISSUE TITLE
sourcesContent support

### ISSUE THREAD

**Issue by mattrobenolt** [mattrobenolt/sourcemap-validator#3]
If a `sourcesContent` array exists in the map, that should take priority over all of the remote sources.

See: http://sourcemap-validator.herokuapp.com/validate?url=http%3A%2F%2Fbookcision.s3.amazonaws.com%2Fsourcemap-validator-testfiles%2Fbookcision.debug.js

**Comment by OliverJAsh** [comment]
Is this still not supported?

My example: http://sourcemap-validator.herokuapp.com/validate?url=https%3A%2F%2Fassets.guim.co.uk%2Fjavascripts%2Fd0d89cc5fb77527f1048d24303565888%2Fcore.js

**Comment by mattrobenolt** [comment]
Hmm, it should work since 039b3dfb7c9c8727af8f5814c1e10470ce8d61e8, so lemme look.

**Comment by OliverJAsh** [comment]
Maybe it does, and my source map is borked!

**Comment by mattrobenolt** [comment]
That's my current thought, so investigating. :)

**Comment by mattrobenolt** [comment]
@OliverJAsh So one problem is the fact that you have multiple `sourceMappingURL` pragmas. It is somehow picking the right one in heroku, but when I'm running locally, it's picking up the other, which is making it harder to debug. :)

**Comment by mattrobenolt** [comment]
Oh, haha, was looking at the wrong thing. There's one Error: https://sourcemap-validator.herokuapp.com/validate?url=https%3A%2F%2Fassets.guim.co.uk%2Fjavascripts%2Fd0d89cc5fb77527f1048d24303565888%2Fcore.js#errors

**Comment by cspeer** [comment]
Hi there,

this still seems to be an issue:
https://sourcemaps.io/validate?url=http%3A%2F%2Fpreview.atameo.com%2Fjavascripts%2Fmodules%2Fapplication.510b4fdd.js

My source-map provides `sourcesContent` butt still the validator appears to be running against what's in `sources`:
`
SourceMap thinks that line 3 of /home/runner/Atameo/dist/server/javascripts/atmo.586bcd84.js is a thing, but it's not.
`

Or am I supposed to leave `sources` blank when `sourcesContent` is provided?

Thanks :)
