### ISSUE TITLE
The UX is tricky

### ISSUE THREAD

**Issue by vasco3** [mattrobenolt/sourcemap-validator#9]
Since it is a source map validator I was trying to upload my sourcemap file instead of the JS.
Was scratching my head for a while, until I figured out I had to use the .js url that points to the source map.

The instructions could be a bit more clear.

Great tool! Thanks for sharing

**Comment by mattrobenolt** [comment]
I'm assuming this wasn't clear?

![image](https://cloud.githubusercontent.com/assets/375744/13337304/7cb1dfd2-dbcf-11e5-93bd-a73a46e711fe.png)

The examples are all js files.

**Comment by vasco3** [comment]
it's ok, just sharing my user experience...
might be the same for other users

**Comment by mattrobenolt** [comment]
I'm not discrediting. Just asking for a suggestion here since I thought it was pretty clear personally.

Do you have any ideas?

**Comment by vasco3** [comment]
What about something like...

<img width="771" alt="screen shot 2016-02-25 at 10 55 18 pm" src="https://cloud.githubusercontent.com/assets/804301/13345390/4c04a3bc-dc13-11e5-971b-baa3aadc60df.png">
